# Generated by Django 5.0.6 on 2024-06-28 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_mascota_delete_persona'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mascota',
        ),
    ]
