# Generated by Django 5.0.6 on 2024-07-09 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0011_compraproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='estado_envio',
            field=models.CharField(choices=[('en_proceso', 'En Proceso'), ('enviado', 'Enviado'), ('cancelado', 'Cancelado')], default='en_proceso', max_length=20),
        ),
    ]
